{% set name = "csp" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name [0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f08c0ca0a116c4f3fd189453ff0cfd80a8179ee8d6f58e1da536b2d618b6e794

build:
  number: 1
  # conda-build fails to find .pyd files co-located next to each other whereas the windows
  # DLL loader does.
  error_overlinking: false   # [win]
  script:
    - export CSP_USE_VCPKG=0  # [not win]
    - {{ PYTHON }} -m pip install . -vv --no-deps  # [not win]
    - set CSP_GENERATOR=Visual Studio 16 2019  # [win]
    - set CSP_USE_VCPKG=0  # [win]
    - {{ PYTHON }} setup.py build_ext install --single-version-externally-managed  --record=record.txt  # [win]
  rpaths:
    - {{ SP_DIR }}/csp/lib  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - bison  # [not win]
    - flex  # [not win]
  host:
    - python
    - brotli
    - cmake
    - cyrus-sasl
    - exprtk
    - gtest
    - libarrow =16
    - libboost-headers
    - libparquet =16
    - libprotobuf
    - librdkafka
    - lz4-c
    - numpy
    - openssl
    - pip
    - pyarrow =16
    - rapidjson
    - ruamel.yaml
    - scikit-build
    - setuptools >=69
    - websocketpp
    - zlib
  run:
    - python
    - backports.zoneinfo  # [py<39]
    - openssl
    - packaging
    - pandas <2.2
    - pyarrow =16
    - psutil
    - pytz
    - rapidjson
    - ruamel.yaml
    - sqlalchemy

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - csp

about:
  home: http://github.com/point72/csp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: csp is a high performance reactive stream processing library, written in C++ and Python
  description: csp is a high performance reactive stream processing library, written in C++ and Python
  dev_url: https://github.com/point72/csp

extra:
  recipe-maintainers:
    - ptomecek
    - alexddobkin
    - robambalu
    - AdamGlustein
    - timkpaine
