{% set name = "csp" %}
{% set version = "0.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name [0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 53258f6359df7bb94e7a581f3c0aee7dd483d4dcf11708c6a2c8b74d1a18b30d

build:
  number: 1
  skip: true  # [win]
  script:
    - export CSP_USE_VCPKG=0  # [not win]
    - {{ PYTHON }} -m pip install . -vv --no-deps  # [not win]
    - set PSP_GENERATOR=Visual Studio 16 2019  # [win]
    - set CSP_USE_VCPKG=0  # [win]
    - {{ PYTHON }} setup.py build_ext install --single-version-externally-managed  --record=record.txt  # [win]
  rpaths:
    - {{ SP_DIR }}/csp/lib

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - bison
    - flex
  host:
    - python
    - brotli
    - cmake
    - cyrus-sasl
    - exprtk
    - gtest
    - libarrow =15
    - libboost-headers
    - libparquet =15
    - libprotobuf
    - librdkafka
    - lz4-c
    - numpy
    - openssl
    - pip
    - pyarrow =15
    - rapidjson
    - ruamel.yaml
    - scikit-build
    - setuptools >=69
    - websocketpp
    - zlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - backports.zoneinfo  # [py<39]
    - openssl
    - packaging
    - pandas <2.2
    - pyarrow =15
    - psutil
    - pytz
    - rapidjson
    - ruamel.yaml
    - sqlalchemy

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - csp

about:
  home: http://github.com/point72/csp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: csp is a high performance reactive stream processing library, written in C++ and Python
  description: csp is a high performance reactive stream processing library, written in C++ and Python
  dev_url: https://github.com/point72/csp

extra:
  recipe-maintainers:
    - ptomecek
    - alexddobkin
    - robambalu
    - AdamGlustein
    - timkpaine
