{% set name = "csp" %}
{% set version = "0.0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name [0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: afe4ea19455fd86bec7bda9fd3fb52a3c029468f8847db033823287e601af1ea
  patches:
    - patches/0001-remove-autogen.patch  # [build_platform != target_platform]

build:
  number: 3
  # conda-build fails to find .pyd files co-located next to each other whereas the windows
  # DLL loader does.
  error_overlinking: false  # [win]
  script:
    # We can't cross-compile on csp due to https://github.com/Point72/csp/issues/264
    # So we "fake it" and use pregenerated files
    - mkdir -p $SRC_DIR/_skbuild/macosx-10.15-arm64-{3.8,3.9,3.10,3.11,3.12}/cmake-build/cpp/csp/engine/csp_autogen/  # [build_platform != target_platform]
    - mkdir -p $SRC_DIR/_skbuild/macosx-10.15-arm64-{3.8,3.9,3.10,3.11,3.12}/cmake-build/cpp/csp/adapters/websocket/csp_autogen/  # [build_platform != target_platform]
    - cp $RECIPE_DIR/patches/engine/{autogen_types.cpp,autogen_types.h} $SRC_DIR/_skbuild/macosx-10.15-arm64-3.8/cmake-build/cpp/csp/engine/csp_autogen/  # [build_platform != target_platform]
    - cp $RECIPE_DIR/patches/engine/{autogen_types.cpp,autogen_types.h} $SRC_DIR/_skbuild/macosx-10.15-arm64-3.9/cmake-build/cpp/csp/engine/csp_autogen/  # [build_platform != target_platform]
    - cp $RECIPE_DIR/patches/engine/{autogen_types.cpp,autogen_types.h} $SRC_DIR/_skbuild/macosx-10.15-arm64-3.10/cmake-build/cpp/csp/engine/csp_autogen/  # [build_platform != target_platform]
    - cp $RECIPE_DIR/patches/engine/{autogen_types.cpp,autogen_types.h} $SRC_DIR/_skbuild/macosx-10.15-arm64-3.11/cmake-build/cpp/csp/engine/csp_autogen/  # [build_platform != target_platform]
    - cp $RECIPE_DIR/patches/engine/{autogen_types.cpp,autogen_types.h} $SRC_DIR/_skbuild/macosx-10.15-arm64-3.12/cmake-build/cpp/csp/engine/csp_autogen/  # [build_platform != target_platform]
    - cp $RECIPE_DIR/patches/adapters/websocket/{websocket_types.cpp,websocket_types.h} $SRC_DIR/_skbuild/macosx-10.15-arm64-3.8/cmake-build/cpp/csp/adapters/websocket/csp_autogen/  # [build_platform != target_platform]
    - cp $RECIPE_DIR/patches/adapters/websocket/{websocket_types.cpp,websocket_types.h} $SRC_DIR/_skbuild/macosx-10.15-arm64-3.9/cmake-build/cpp/csp/adapters/websocket/csp_autogen/  # [build_platform != target_platform]
    - cp $RECIPE_DIR/patches/adapters/websocket/{websocket_types.cpp,websocket_types.h} $SRC_DIR/_skbuild/macosx-10.15-arm64-3.10/cmake-build/cpp/csp/adapters/websocket/csp_autogen/  # [build_platform != target_platform]
    - cp $RECIPE_DIR/patches/adapters/websocket/{websocket_types.cpp,websocket_types.h} $SRC_DIR/_skbuild/macosx-10.15-arm64-3.11/cmake-build/cpp/csp/adapters/websocket/csp_autogen/  # [build_platform != target_platform]
    - cp $RECIPE_DIR/patches/adapters/websocket/{websocket_types.cpp,websocket_types.h} $SRC_DIR/_skbuild/macosx-10.15-arm64-3.12/cmake-build/cpp/csp/adapters/websocket/csp_autogen/  # [build_platform != target_platform]
    - export CSP_USE_VCPKG=0  # [not win]
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation  # [not win]
    - set CSP_GENERATOR=Visual Studio 16 2019  # [win]
    - set CSP_USE_VCPKG=0  # [win]
    - {{ PYTHON }} setup.py build_ext install --single-version-externally-managed  --record=record.txt  # [win]
  rpaths:
    - {{ SP_DIR }}/csp/lib  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [not win]
    - bison  # [not win]
    - flex  # [not win]
  host:
    - python
    - brotli
    - cmake
    - cyrus-sasl
    - exprtk
    - gtest
    - libarrow =16
    - libboost-headers
    - libparquet =16
    - libprotobuf
    - librdkafka
    - lz4-c
    - numpy
    - openssl
    - pip
    - pyarrow =16
    - rapidjson
    - ruamel.yaml
    - scikit-build
    - setuptools >=69
    - websocketpp
    - zlib
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - backports.zoneinfo  # [py<39]
    - openssl
    - packaging
    - pandas
    - pyarrow =16
    - psutil
    - pytz
    - rapidjson
    - ruamel.yaml
    - sqlalchemy

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - csp

about:
  home: http://github.com/point72/csp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: csp is a high performance reactive stream processing library, written in C++ and Python
  description: csp is a high performance reactive stream processing library, written in C++ and Python
  dev_url: https://github.com/point72/csp

extra:
  recipe-maintainers:
    - ptomecek
    - alexddobkin
    - robambalu
    - AdamGlustein
    - timkpaine
